; Open Control Framework - Unit Tests
;
; Usage: CXX=clang++ CC=clang pio test -e native

[platformio]
default_envs = native

[env:native]
platform = native
build_flags =
    -std=c++17
    -I src
test_build_src = yes
